version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./data:/app/data
      - ./models:/app/models
      - ./reports:/app/reports
      - ./logs:/app/logs
    environment:
      - MLFLOW_TRACKING_URI=file:///app/mlruns
      - MLFLOW_REGISTRY_URI=file:///app/mlruns
    command: uvicorn telecommunication.api.main:app --host 0.0.0.0 --port 8000 --reload

  mlflow:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
    command: mlflow ui --host 0.0.0.0 --port 5000 