# Data Split Parameters
split:
  test_size: 0.2
  random_state: 42

model:
  n_estimators: 100
  random_state: 1234

# model:
#   random_state: 42
#   n_estimators_grid: [100, 200, 300]
#   max_depth_grid: [10, 20, 30, null]
#   min_samples_split_grid: [2, 5, 10]
#   min_samples_leaf_grid: [1, 2, 4]

# # Feature Engineering Parameters
# features:
#   min_internet_gb: 0.1
#   max_validity_days: 30

# # Training Parameters
# training:
#   batch_size: 32
#   epochs: 100
#   learning_rate: 0.001