# Data Split Parameters
split:
  test_size: 0.2
  random_state: 42

models:
  RandomForest:
    model_type: "RandomForest"
    random_state: 42
    params:
      n_estimators_grid: [100, 200, 300]
      max_depth_grid: [10, 20, 30, null]
      min_samples_split_grid: [2, 5, 10]
      min_samples_leaf_grid: [1, 2, 4]

  GradientBoosting:
    model_type: "GradientBoosting"
    random_state: 42
    params:
      n_estimators_grid: [100, 200, 300]
      learning_rate_grid: [0.01, 0.1, 0.3]
      max_depth_grid: [3, 5, 7]
      min_samples_split_grid: [2, 5, 10]

  LinearRegression:
    model_type: LinearRegression
    params:
      fit_intercept_grid: [true, false]
      positive_grid: [true, false]

  DecisionTree:
    model_type: "DecisionTree"
    random_state: 42
    params:
      max_depth_grid: [5, 10, 15, 20]
      min_samples_split_grid: [2, 5, 10]
      min_samples_leaf_grid: [1, 2, 4]
  
  # SVM:
  #   model_type: "SVM"
  #   params:
  #     C_grid: [0.1, 1, 10, 100]
  #     kernel_grid: ["linear", "rbf"]
  #     gamma_grid: ["scale", "auto", 0.1, 1]
  #     epsilon_grid: [0.1, 0.2, 0.5]

  # XGBoost:
  #   model_type: "XGBoost"
  #   random_state: 42
  #   params:
  #     n_estimators_grid: [100, 200, 300]
  #     learning_rate_grid: [0.01, 0.1, 0.3]
  #     max_depth_grid: [3, 5, 7]
  #     min_child_weight_grid: [1, 3, 5]

training:
  target_column: "commission"
  cv_folds: 5
  n_iter_search: 10